# Generated by Django 3.1.4 on 2020-12-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productor', '0003_productor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productor',
            options={},
        ),
    ]
